# Generated by Django 5.0.2 on 2024-03-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
