# Generated by Django 5.0.2 on 2024-03-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicApp', '0002_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('domicilio', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
